class Constants:

#window stuff
    WINDOWHEIGHT = 900
    WINDOWWIDTH = 900

    STARTINGFOODS = int((WINDOWHEIGHT * WINDOWWIDTH) / 130000)

    WINDOWCENTER = (int(WINDOWWIDTH / 2), int(WINDOWHEIGHT / 2))

#player stuff
    PLAYERWIDTH = 100
    PLAYERHEIGHT = 100

    PLAYERMOVESPEED = 10

    PLAYERINFLATION = 10

    PLAYERNAME = 'kappa'

#camera stuff
    CAMERASLACK = 280
    CAMERAMOVESPEED = 8

    PLAYERCAMSIZE = 100

#food stuff
    FOODMAXSIZE = 90
    FOODMINSIZE = 25

    MAXFOODQUANTITY = 20